// This file is part of Codemancer.
// Copyright 2014-2016 Graham Shaw.
// Distribution and modification are permitted within the terms of the
// GNU General Public License (version 3 or any later version).

package org.codemancer.db.jpa;

import javax.persistence.Entity;

/** A class to represent a comment. */
@Entity
public class Comment extends Fact implements org.codemancer.db.Comment {
	/** The address of the instruction to which this comment applies. */
	private final long addr;

	/** True if this is an autogenerated comment, otherwise false. */
	private final boolean auto;

	/** The content of this comment. */
	private final String content;

	/** Construct empty comment.
	 * A default constructor is required by the JPA.
	 */
	protected Comment() {
		super();
		this.addr = 0;
		this.auto = false;
		this.content = null;
	}

	/** Construct comment.
	 * @param minRev the lowest revision number for which this line is present
	 * @param maxRev the highest revision number for which this line is present
	 * @param addr the address of the instruction to which this comment applies
	 * @param auto true if this is an autogenerated comment, otherwise false
	 * @param content the content of this comment
	 */
	protected Comment(long minRev, long maxRev, long addr, boolean auto, String content) {
		super(minRev, maxRev);
		this.addr = addr;
		this.auto = auto;
		this.content = content;
	}

	/** Get address.
	 * @return the address of the instruction to which this comment applies
	 */
	public final long getAddr() {
		return addr;
	}

	/** Check whether this is an autogenerated comment.
	 * @return true if autogenerated, otherwise false
	 */
	public final boolean getAuto() {
		return auto;
	}

	/** Get content.
	 * @return the content of this comment
	 */
	public final String getContent() {
		return content;
	}
}
